name: CICD
on: push
jobs:
  cicd:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write, id-token: write }
    steps:
      - uses: internetarchive/cicd@v1
        with:
          BASE_DOMAIN: 'hijack.lab'
          NOMAD_ADDR: 'http://nomad.hijack.lab'
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
